sudo: false
language: rust
rust:
- nightly
- beta
- stable
- 1.8.0
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: CA1F77a8gM55PMui1Hw4tdRAJvucb2H2uMo5lqPFEKM3zxRSd5qOpessOLEEs5ahoUYOLSseXIkptiNnIY8Hf6BRY64t6jNJHS2csgRsVCZDaUWOfdtFnzY62t8Jze7ZNxKKXp8/C382bpSO6KF0xZMUsXBiDfCQVaa4cbaU16Bs6glJCg5+BAGGCwwYfKnstNp1QSxInvwNhkfh49bVuIPHe8V/sGKEaxM/s6ksJpxAg/3GDXVzDUdEQKNUXMidW45gBVQ3i7XJpe00Yodp1hGxZaQodLzS2/lysQSrgxXsyMKW1aDKrCmlJjhOylK1uQEunHH5g7HcKmwZd/oCfGzOwYl8qG+kzlNQNtmctckx9PMBi+MwjvB7eLh4z+Ja0qK/jR6aMygK1al5CoMRonfmLmq2bZv8bUxba6sQAvPvMTLyf5U7iWFtSNWFfFuu1KxEuXNaJu7GPm/hQ3SGmw8HXBxaFM1Wc6VhVPYL9NySXpykWKUz/fKnNu27OF+8rGlYcGsIhrHEder5TkUomGJBBHbzGE7hBj0btjjKXXvQkBOTpxAWRHM2f6+rjPXnO53TDHxHicE9YAsmrAqyqFOvMgNX/CljsSztp77vR0QLfJXmFeLgv0+R1cNj2RkDOR9irqw93ahXf4SAqy72n8DZ+zvSp4q3Tij4IVAzYVw=
